# Onboarding {#onboarding}

## Code of conduct

[Adopted from the Fisheries Integrated modeling Collaborative Workflow document]https://noaa-fims.github.io/collaborative_workflow/code-of-conduct.html#fims-contributor-conduct)

All contributors participating and contributing to the afsc-assessments organization and related projects project are expected to adhere to the [Contributor Covenant](https://www.contributor-covenant.org/version/2/1/code_of_conduct/). Briefly, these standards are adopted to ensure a positive and harassment-free environment for all participants. Examples of behavior that contributes to a positive environment for our community include:

Demonstrating empathy and kindness toward other people
Being respectful of differing opinions, viewpoints, and experiences
Giving and gracefully accepting constructive feedback
Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience
Focusing on what is best not just for us as individuals, but for the overall community


## AFSC Best Practices

Propose following something similar to [FIMS](https://noaa-fims.github.io/collaborative_workflow/contributor-guidelines.html#contributor-guidelines): 

### Git and GitHub 

Link to trainings, resources for online learning

AFSC POC for github? NOAA/NMFS rules?

### File directory

Data pulling group?

### Coding style guide


